// <auto-generated />
using System;
using BlazorApp1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BlazorApp1.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "plug",
                            Name = "Plugs",
                            Url = "plugs"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "cable",
                            Name = "Cables",
                            Url = "cables"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "phone",
                            Name = "Phones",
                            Url = "phones"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "GUARANTEED 55% CHARGE FOR IPHONE/IPAD (DEPENDENT IF CABLE IS POWER DELIVERY COMPATIBLE) • USB Wall Charger: Simply plug into any wall adapter and charge your devices • Ultra-Portable:  Carry your plug everywhere, it is perfect for both homes & offices • Safe & Reliable: Extremely safe & dependable, features Over-current, over-voltage and short-circuit protection • Heat Resistant: It is made using fireproof ABS plastic which has a high melting and heating point, protecting your connected devices. • Smart Current Detection: Smart current detection which enables swift & safe charging Output – 20W Fast Charging USB port The built-in safety systems protect your devices from overcharging and short-circuit. With Smart IC functionality, it recognizes the attached gadget and automatically delivers the correct amount of power.",
                            Image = "https://cdn.shopify.com/s/files/1/0314/9738/8165/products/DEV-20WPD-PLUG-WHT_md_720x.jpg?v=1612450879",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 12.99m,
                            Price = 9.99m,
                            Title = "Devia – 20W Type C Power Delivery 3-Pin UK Charging Plug – White"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guaranteed 50% charge in 30 minutes charged for all iOS devices (This cable can only provide this result along with using the Power Delivery Plug) – Power Delivery: Use this cable with your USB-C Power Delivery charger (including Apple 29W, 30W, 61W, or 87W USB-C Power Adapter) to charge your iOS device, and access fast charging for iPhone 8, 8 Plus, X, XS, XR, XS Max, iPads, and more. – Staying Power: Lasts 30× longer than ordinary cables. Proven in a laboratory environment to withstand 30,000 bends. – MFi: MFi certification and strict quality testing ensure your Apple devices are charged safely, at their fastest possible speed. – With this Lightning to USB C cable, you can not only use a PD Power Adapter but also the mobile power supply to recharge your iPhone. It’s worth mentioning that it also supports fast charge and data transfer your iPhone from a USB-C laptop or desktop directly. And the data transfer rates up to 480Mbps, 1G large files will be finished in 25s. Perfect choice to take advantage of fast charging with existing USB-C PD charger for your newest Apple devices.",
                            Image = "https://armafone.com/wp-content/uploads/2020/10/Devia-1.5m-18W-Power-Delivery-Type-C-to-MFI-Lightning-Cable-White-1-1.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0m,
                            Price = 7.45m,
                            Title = "Devia – 1.5m (18W) Power Delivery – Type C to MFI Lightning Cable – White"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Product", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
